### ISSUE TITLE
F1 score

### ISSUE THREAD

**Issue by Stubborn-z** [SapienzaNLP/esc#4]
Hi, I would like to ask how the F1 score of the noun，verb， adjective and adverb is obtained ？

**Comment by edobobo** [comment]
Basically, we partitioned the "ALL" datasets from the Raganato et al. 2017 framework using the Part of Speech tags of the instances.

**Comment by Stubborn-z** [comment]
Thank you, but after separating the parts of speech, how do you get their F1 scores?

**Comment by edobobo** [comment]
You can use the evaluation script. It is explained in the README. I hope I got the question right this time 😄

**Comment by Stubborn-z** [comment]
Yes haha ​​! I did get the F1 score of "ALL" datasets through the script file, but I still don't know how to get the F1 score of the specific part of speech. Is it obtained using statistical methods?

**Comment by edobobo** [comment]
Ok, let's see if I can be more clear xD.

1. **You** have to partition the ALL dataset by yourself using the PoS of each instance (If I find the script I used, I'll put it into the repo).
2. Let's say that you created the four datasets. The one containing nouns, for example, should be composed of two files: noun.data.xml and noun.gold.key.txt (Exactly like ALL)
3. Now, you can evaluate ESCHER checkpoints on those datasets using this script (e.g., for nouns)
`PYTHONPATH=$(pwd) python esc/predict.py --ckpt <escher_checkpoint.ckpt> --dataset-paths data/ALL-partition/noun.data.xml --prediction-types probabilistic`

I am a little bit busy at the moment, but I'll try to push the script for the PoS-based partitioning asap.

**Comment by Stubborn-z** [comment]
Got it. Thank you  very much!
